# Generated by Django 3.1.12 on 2026-01-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_bookedmovie_booking_date_alter_bookedmovie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tconst', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('startYear', models.IntegerField()),
                ('runtimeMinutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(max_length=255)),
                ('averageRating', models.FloatField(blank=True, null=True)),
                ('numVotes', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookedmovie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
